const geojsonFiles = [
  'data/Andrychów.geojson',
  'data/Bochnia.geojson',
  'data/Chrzanów.geojson',
  'data/Gorlice.geojson',
  'data/Kraków.geojson',
  'data/Krynica-Zdrój.geojson',
  'data/Kęty.geojson',
  'data/Libiąż.geojson',
  'data/malopolskie.geojson',
  'data/Myślenice.geojson',
  'data/Nowy Sącz.geojson',
  'data/Nowy Targ.geojson',
  'data/Olkusz.geojson',
  'data/Oświęcim.geojson',
  'data/Piwniczna-Zdrój.geojson',
  'data/Skawina.geojson',
  'data/Tarnów.geojson',
  'data/Trzebinia.geojson',
  'data/Wadowice.geojson',
  'data/Wieliczka.geojson',
  'data/Zakopane.geojson',
  'data/Łomnica-Zdrój.geojson'
];