const geojsonFiles = [
  'data/Alwernia.geojson',
  'data/Andrychów.geojson',
  'data/Andrzejówka.geojson',
  'data/Banica.geojson',
  'data/Barcice Dolne.geojson',
  'data/Barcice.geojson',
  'data/Barnowiec.geojson',
  'data/Biadoliny Szlacheckie.geojson',
  'data/Biecz.geojson',
  'data/Bielcza.geojson',
  'data/Bilczyce.geojson',
  'data/Biskupice.geojson',
  'data/Blechnarka.geojson',
  'data/Bobowa.geojson',
  'data/Bochnia.geojson',
  'data/Bogucice.geojson',
  'data/Borzęcin.geojson',
  'data/Bratucice.geojson',
  'data/Brzeg.geojson',
  'data/Brzegi.geojson',
  'data/Brzesko.geojson',
  'data/Brzeszcze.geojson',
  'data/Brzeźnica.geojson',
  'data/Bukowno.geojson',
  'data/Buków.geojson',
  'data/Chełmek.geojson',
  'data/Chrzanów.geojson',
  'data/Ciche.geojson',
  'data/Ciężkowice.geojson',
  'data/Czarna Góra.geojson',
  'data/Czchów.geojson',
  'data/Czerwienne.geojson',
  'data/Dobczyce.geojson',
  'data/Drwinia.geojson',
  'data/Dubne.geojson',
  'data/Dzianisz.geojson',
  'data/Dziewin.geojson',
  'data/Dąbrowa Tarnowska.geojson',
  'data/Dębica.geojson',
  'data/Dębno.geojson',
  'data/Gdów.geojson',
  'data/Gnojnik.geojson',
  'data/Gorlice.geojson',
  'data/Grabie.geojson',
  'data/Grodków.geojson',
  'data/Grybów.geojson',
  'data/Głębokie.geojson',
  'data/Iwkowa.geojson',
  'data/Izby.geojson',
  'data/Jadowniki.geojson',
  'data/Jastrzębik.geojson',
  'data/Jaworki.geojson',
  'data/Jazowsko.geojson',
  'data/Jordanów.geojson',
  'data/Kacwin.geojson',
  'data/Kalwaria Zebrzydowska.geojson',
  'data/Kamionna.geojson',
  'data/Kokotów.geojson',
  'data/Kokuszka.geojson',
  'data/Kościelisko.geojson',
  'data/Kraków.geojson',
  'data/Krosno.geojson',
  'data/Krynica-Zdrój.geojson',
  'data/Krzeszowice.geojson',
  'data/Królówka.geojson',
  'data/Kęty.geojson',
  'data/Kłaj.geojson',
  'data/Lanckorona.geojson',
  'data/Leluchów.geojson',
  'data/Lewin Brzeski.geojson',
  'data/Libiąż.geojson',
  'data/Limanowa.geojson',
  'data/Lipnica Murowana.geojson',
  'data/Lubsza.geojson',
  'data/Maków Podhalański.geojson',
  'data/Małe Ciche.geojson',
  'data/Miechów.geojson',
  'data/Milik.geojson',
  'data/Mochnaczka Niżna.geojson',
  'data/Mostki.geojson',
  'data/Mszana Dolna.geojson',
  'data/Mucharz.geojson',
  'data/Murzasichle.geojson',
  'data/Muszyna.geojson',
  'data/Muszynka.geojson',
  'data/Myślec.geojson',
  'data/Myślenice.geojson',
  'data/Mąkoszyce.geojson',
  'data/Młodów.geojson',
  'data/Nawojowa.geojson',
  'data/Niepołomice.geojson',
  'data/Nowe Brzesko.geojson',
  'data/Nowe Bystre.geojson',
  'data/Nowy Sącz.geojson',
  'data/Nowy Targ.geojson',
  'data/Nowy Wiśnicz.geojson',
  'data/Obłazy Ryterskie.geojson',
  'data/Ochotnica Dolna.geojson',
  'data/Ochotnica Górna.geojson',
  'data/Olkusz.geojson',
  'data/Oświęcim.geojson',
  'data/Piwniczna-Zdrój.geojson',
  'data/Polska.geojson',
  'data/Popowice.geojson',
  'data/Porąbka Iwkowska.geojson',
  'data/Porąbka Uszewska.geojson',
  'data/Powroźnik.geojson',
  'data/Proszowice.geojson',
  'data/Przysietnica.geojson',
  'data/Rabka-Zdrój.geojson',
  'data/Radom.geojson',
  'data/Radłów.geojson',
  'data/Rajbrot.geojson',
  'data/Roczyny.geojson',
  'data/Ropki.geojson',
  'data/Roztoka Ryterska.geojson',
  'data/Ryglice.geojson',
  'data/Rytro.geojson',
  'data/Rzepiska.geojson',
  'data/Rzezawa.geojson',
  'data/Skawina.geojson',
  'data/Skała.geojson',
  'data/Skrudzina.geojson',
  'data/Sobolów.geojson',
  'data/Spytkowice.geojson',
  'data/Stadła.geojson',
  'data/Stary Sącz.geojson',
  'data/Stryszów.geojson',
  'data/Strzelce Wielkie.geojson',
  'data/Sucha Beskidzka.geojson',
  'data/Sucha Struga.geojson',
  'data/Sułkowice.geojson',
  'data/Szczawnica.geojson',
  'data/Szczawnik.geojson',
  'data/Szczucin.geojson',
  'data/Szczurowa.geojson',
  'data/Szlachtowa.geojson',
  'data/Słomniki.geojson',
  'data/Tarnawa.geojson',
  'data/Tarnów.geojson',
  'data/Tomice.geojson',
  'data/Trzciana.geojson',
  'data/Trzebinia.geojson',
  'data/Tuchów.geojson',
  'data/Tylicz.geojson',
  'data/Tymowa.geojson',
  'data/Uszew.geojson',
  'data/Uście Solne.geojson',
  'data/Wadowice.geojson',
  'data/Wieliczka.geojson',
  'data/Wieprz.geojson',
  'data/Wierchomla Mała.geojson',
  'data/Wierchomla Wielka.geojson',
  'data/Wilkowice.geojson',
  'data/Wojkowa.geojson',
  'data/Wojnicz.geojson',
  'data/Wola Krogulecka.geojson',
  'data/Wolbrom.geojson',
  'data/Wysowa-Zdrój.geojson',
  'data/Węgrzce Wielkie.geojson',
  'data/Zaborów.geojson',
  'data/Zakliczyn.geojson',
  'data/Zakopane.geojson',
  'data/Zator.geojson',
  'data/Zubrzyk.geojson',
  'data/Ząb.geojson',
  'data/Złockie.geojson',
  'data/Złota.geojson',
  'data/Złotne.geojson',
  'data/Łapanów.geojson',
  'data/Łapczyca.geojson',
  'data/Łazany.geojson',
  'data/Łazy Biegonickie.geojson',
  'data/Łazy Brzyńskie.geojson',
  'data/Łomnica-Zdrój.geojson',
  'data/Łososina Dolna.geojson',
  'data/Łysa Góra.geojson',
  'data/Świątniki Górne.geojson',
  'data/Żabno.geojson',
  'data/Żegiestów.geojson',
  'data/Żegocina.geojson',
  'data/Żeleźnikowa Mała.geojson',
  'data/Żeleźnikowa Wielka.geojson'
];