const geojsonFiles = [
  'data/Alwernia.geojson',
  'data/Andrychów.geojson',
  'data/Andrzejówka.geojson',
  'data/Banica.geojson',
  'data/Biecz.geojson',
  'data/Biskupice.geojson',
  'data/Blechnarka.geojson',
  'data/Bobowa.geojson',
  'data/Bochnia.geojson',
  'data/Brzesko.geojson',
  'data/Brzeszcze.geojson',
  'data/Brzeźnica.geojson',
  'data/Bukowno.geojson',
  'data/Chełmek.geojson',
  'data/Chrzanów.geojson',
  'data/Ciche.geojson',
  'data/Ciężkowice.geojson',
  'data/Czarna Góra.geojson',
  'data/Czchów.geojson',
  'data/Czerwienne.geojson',
  'data/Dobczyce.geojson',
  'data/Dubne.geojson',
  'data/Dzianisz.geojson',
  'data/Dąbrowa Tarnowska.geojson',
  'data/Dębica.geojson',
  'data/Gdów.geojson',
  'data/Gorlice.geojson',
  'data/Grybów.geojson',
  'data/Izby.geojson',
  'data/Jastrzębik.geojson',
  'data/Jordanów.geojson',
  'data/Kacwin.geojson',
  'data/Kalwaria Zebrzydowska.geojson',
  'data/Kokotów.geojson',
  'data/Kokuszka.geojson',
  'data/Kościelisko.geojson',
  'data/Kraków.geojson',
  'data/Krynica-Zdrój.geojson',
  'data/Krzeszowice.geojson',
  'data/Kęty.geojson',
  'data/Kłaj.geojson',
  'data/Lanckorona.geojson',
  'data/Leluchów.geojson',
  'data/Libiąż.geojson',
  'data/Limanowa.geojson',
  'data/Maków Podhalański.geojson',
  'data/Małe Ciche.geojson',
  'data/Miechów.geojson',
  'data/Milik.geojson',
  'data/Mochnaczka Niżna.geojson',
  'data/Mszana Dolna.geojson',
  'data/Mucharz.geojson',
  'data/Murzasichle.geojson',
  'data/Muszyna.geojson',
  'data/Muszynka.geojson',
  'data/Myślenice.geojson',
  'data/Młodów.geojson',
  'data/Niepołomice.geojson',
  'data/Nowe Bystre.geojson',
  'data/Nowy Sącz.geojson',
  'data/Nowy Targ.geojson',
  'data/Nowy Wiśnicz.geojson',
  'data/Olkusz.geojson',
  'data/Oświęcim.geojson',
  'data/Piwniczna-Zdrój.geojson',
  'data/Powroźnik.geojson',
  'data/Proszowice.geojson',
  'data/Rabka-Zdrój.geojson',
  'data/Radłów.geojson',
  'data/Roczyny.geojson',
  'data/Ryglice.geojson',
  'data/Rzepiska.geojson',
  'data/Skawina.geojson',
  'data/Skała.geojson',
  'data/Spytkowice.geojson',
  'data/Stary Sącz.geojson',
  'data/Stryszów.geojson',
  'data/Sucha Beskidzka.geojson',
  'data/Sułkowice.geojson',
  'data/Szczawnica.geojson',
  'data/Szczawnik.geojson',
  'data/Szczucin.geojson',
  'data/Słomniki.geojson',
  'data/Tarnów.geojson',
  'data/Tomice.geojson',
  'data/Trzebinia.geojson',
  'data/Tuchów.geojson',
  'data/Tylicz.geojson',
  'data/Wadowice.geojson',
  'data/Wieliczka.geojson',
  'data/Wieprz.geojson',
  'data/Wierchomla Mała.geojson',
  'data/Wierchomla Wielka.geojson',
  'data/Wilkowice.geojson',
  'data/Wojkowa.geojson',
  'data/Wojnicz.geojson',
  'data/Wolbrom.geojson',
  'data/Wysowa-Zdrój.geojson',
  'data/Węgrzce Wielkie.geojson',
  'data/Zakliczyn.geojson',
  'data/Zakopane.geojson',
  'data/Zator.geojson',
  'data/Złockie.geojson',
  'data/Łomnica-Zdrój.geojson',
  'data/Świątniki Górne.geojson',
  'data/Żabno.geojson',
  'data/Żegiestów.geojson'
];